on:
  workflow_call:
    secrets:
      GIT_PR_RELEASE_TOKEN:
        required: true

jobs:
  create-release-pr:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Create a release pull request
      env:
        GIT_PR_RELEASE_TOKEN: ${{ secrets.GIT_PR_RELEASE_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: main
        GIT_PR_RELEASE_BRANCH_STAGING: develop
        GIT_PR_RELEASE_LABELS: release,ignore-for-release-note
        GIT_PR_RELEASE_TEMPLATE: .github/git_pr_release_template
      run: |
        gem install -N git-pr-release -v "2.2.0"
        git-pr-release --no-fetch
